version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trading
      MYSQL_USER: trader
      MYSQL_PASSWORD: traderpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    environment:
      INFLUXDB_DB: market_data
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: adminpass
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./flask_app
    container_name: algo_backend
    restart: always
    depends_on:
      - db
      - influxdb
      - redis
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./flask_app:/app

  frontend:
    build: ./frontend/trading-dashboard
    container_name: trading_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/trading-dashboard:/app
      - /app/node_modules

volumes:
  mysql_data:
  influxdb_data:
  redis_data:
