version: "1.0"

bot:
  name: "AlgoTradingBot"
  mode: "live"  # Options: 'live', 'paper', 'backtest'
  log_level: "INFO"
  max_concurrent_trades: 5


paths:
  root_dir: "/home/pysunny/PycharmProjects/algoTradingBot"
  config_dir: "${paths.root_dir}/config"
  data_dir: "${paths.root_dir}/data"


trading:
  library:
    name: "talib"  # Options: 'backtrader', 'quantlib', 'quantconnect', 'quantopian', 'zipline', 'pandas_ta', 'talib'

  symbols:
    - "NSE:NIFTY50-INDEX"
    - "NSE:RELIANCE"
    - "NSE:TCS"
  active_strategy: EMA_Crossover  # Change this to test different strategies # default (EMA_Crossover)

  strategies:
    EMA_Crossover:
      ema_short: 9
      ema_long: 21
      stop_loss: 1.5
      target: 3.0

    RSI_Crossover:
      rsi_period: 14
      rsi_overbought: 70
      rsi_oversold: 30
      higher_tf_rsi_period: 21  # Multi-timeframe RSI confirmation
      trailing_sl: 0.02  # 2% Trailing Stop-Loss
      stop_loss: 2.0
      target: 4.0

    MACD_Crossover:
      macd_fast: 12
      macd_slow: 26
      macd_signal: 9
      stop_loss: 1.8
      target: 3.5

    RSI_MACD_Crossover:
      rsi_period: 14
      rsi_overbought: 70
      rsi_oversold: 30
      macd_fast: 12
      macd_slow: 26
      macd_signal: 9
      stop_loss_pct: 0.02
      take_profit_pct: 0.05
      trailing_sl_pct: 0.02  # 2% Trailing Stop-Loss

    EMA_RSI_Crossover:
      ema_short: 9         # Short-term EMA
      ema_long: 21         # Long-term EMA
      rsi_period: 14       # RSI period
      rsi_overbought: 70   # RSI overbought threshold
      rsi_oversold: 30     # RSI oversold threshold
      stop_loss: 1.5       # Stop loss percentage
      target: 3.0          # Target percentage
      risk_per_trade: 2.0  # Risk per trade (as % of capital)
      position_size: 10    # Number of shares per trade

    risk_management:
      stop_loss: 0.02  # 2% stop loss
      take_profit: 0.05 # 5% target profit
      trailing_stop_loss: 0.01 # 1% trailing SL

backtesting:
  capital: 100000
  commission: 0.001  # 0.1% per trade
  slippage: 0.0005  # 0.05% per trade

paper_trading:
  capital: 100000
  commission: 0.001  # 0.1% per trade
  slippage: 0.0005  # 0.05% per trade

live_trading:
  capital: 100000
  commission: 0.001  # 0.1% per trade
  slippage: 0.0005  # 0.05% per trade

# You can get all the latest symbols of all the exchanges from the symbol master files
exchange_symbols:
  # NSE – Currency Derivatives: Currency Derivatives are futures and options contract where you can buy or sell
  # Specific quantities of a particular currency pair at a pre-determined future date.
  # Currency Derivative Trading is similar to Stock Futures and Options trading.
  nse_cd: https://public.fyers.in/sym_details/NSE_CD.csv

  #  NSE – Equity Derivatives:
  nse_fo: https://public.fyers.in/sym_details/NSE_FO.csv

  # BSE – Capital Market:
  bse_cm: https://public.fyers.in/sym_details/BSE_CM.csv

  # BSE - Equity Derivatives:
  bse_fo: https://public.fyers.in/sym_details/BSE_FO.csv

  # NSE – Capital Market:
  nse_cm: https://public.fyers.in/sym_details/NSE_CM.csv

  # MCX - Commodity:
  mcx_fo: https://public.fyers.in/sym_details/MCX_COM.csv


database:
  mysql:
    name: "fnodatabase"
    historical_data_table: "nifty50_1m"
  influxdb:
    host: "localhost"
    port: 8086
    name: "market_data"
  timescaledb:
    host: "localhost"
    port: 5432
    user: "trading_user"
    password: "secure_password"
    name: "historical_prices"

