version: 1
formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(message)s"
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s"
handlers:
  console:
    class: "logging.StreamHandler"
    level: "INFO"
    formatter: "simple"
    stream: "ext://sys.stdout"
  file:
    class: "logging.FileHandler"
    level: "DEBUG"
    formatter: "detailed"
    filename: "logs/trading_bot.log"
    mode: "a"
loggers:
  trading_bot:
    level: "DEBUG"
    handlers: ["console", "file"]
    propagate: no
root:
  level: "WARNING"
  handlers: ["console"]
